# Generated by Django 5.0.1 on 2024-02-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_remove_userprofile_user_delete_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
