# Generated by Django 5.0.1 on 2024-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0005_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('BACK', 'BACK-END'), ('FRONT', 'FRONT-END'), ('IOS', 'IOS'), ('AND', 'ANDROID')], default='BACK', max_length=9),
        ),
    ]
