# Generated by Django 5.0.1 on 2024-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0006_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Project 9999'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Title 9999', max_length=100),
            preserve_default=False,
        ),
    ]
