# Generated by Django 5.0.1 on 2024-02-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0014_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
