# Generated by Django 5.0.1 on 2024-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0016_alter_issue_priority_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'TO DO'), ('WIP', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], default=('TODO', 'TO DO'), max_length=11),
        ),
    ]
