# Generated by Django 5.0.1 on 2024-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0018_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bar',
            field=models.IntegerField(blank=True, default=42),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'TO DO'), ('WIP', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], default='TODO', max_length=11),
        ),
    ]
