# Generated by Django 5.0.1 on 2024-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0019_issue_bar_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('TODO', 'TO DO'), ('WIP', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], default='TODO', max_length=11, null=True),
        ),
    ]
