# Generated by Django 5.0.1 on 2024-02-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0021_alter_issue_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='bar',
        ),
    ]
